name = "SemiAnalyticWECs"
uuid = "e38dea05-26d8-438a-8a99-79c6c0704522"
authors = ["Zachary J Wegert"]
version = "1.0.0-DEV"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
BenchmarkTools = "1.6.3"
CairoMakie = "0.15.7"
DataFrames = "1.8.1"
FastGaussQuadrature = "1.1.0"
ForwardDiff = "1.3.0"
JLD2 = "0.6.3"
LinearAlgebra = "1.11.0"
ProgressMeter = "1.11.0"
QuadGK = "2.11.2"
Quadmath = "0.5.13"
Roots = "2.2.10"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
