name = "SemiAnalyticWECs"
uuid = "e38dea05-26d8-438a-8a99-79c6c0704522"
authors = ["Zachary J Wegert"]
version = "1.0.0-DEV"

[deps]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
FastGaussQuadrature = "1.1.0"
ForwardDiff = "1.3.0"
Roots = "2.2.10"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
